# Generated by Django 2.1.1 on 2018-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('title_header', models.CharField(max_length=100, verbose_name='Título cabecera')),
                ('path_image_fixed', models.CharField(max_length=200, verbose_name='Ubicación imagen fija')),
                ('path_image_folder', models.CharField(max_length=200, verbose_name='Ubicacion galería')),
                ('time_duration', models.PositiveSmallIntegerField(verbose_name='Duración de cada imagen (ms)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
